name: beta push onbloc-tx-indexer

on:
  push:
    branches:
      - beta
  workflow_dispatch:

permissions:
  contents: write
  id-token: write
jobs:
  main_batch_db_watcher:
    name: Run tx-indexer app
    uses: ./.github/workflows/app_template.yml
    with:
      app-name: "tx-indexer"
      env: "beta"
    secrets:
      AWS_IAM_OIDC: ${{ secrets.AWS_IAM_OIDC }}
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
      REGION: ${{ secrets.DEV_REGION }}
